import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:hive/hive.dart';
import 'package:injectable/injectable.dart';

import '../../core/aop/aop_leaderboard_repository.dart';
import '../../core/aop/aop_level_repository.dart';
import '../../core/aop/aop_player_repository.dart';
import '../../core/aop/aop_progress_repository.dart';
import '../../features/game/application/use_cases/calculate_score_use_case.dart';
import '../../features/game/application/use_cases/evaluate_game_state_use_case.dart';
import '../../features/game/application/use_cases/load_level_use_case.dart';
import '../../features/game/application/use_cases/start_game_session_use_case.dart';
import '../../features/game/application/use_cases/trigger_arrow_exit_use_case.dart';
import '../../features/game/application/use_cases/undo_move_use_case.dart';
import '../../features/game/application/use_cases/unlock_next_level_use_case.dart';
import '../../features/game/data/models/app_progress_model.dart';
import '../../features/game/data/models/level_model.dart';
import '../../features/game/data/level_definitions/level_definitions.dart';
import '../../features/game/domain/services/collision_validator.dart';
import '../../features/game/domain/repositories/i_level_repository.dart';
import '../../features/game/domain/repositories/i_progress_repository.dart';
import '../../features/game/presentation/bloc/cube3d/cube3d_game_cubit.dart';
import '../../features/game/presentation/bloc/game_bloc.dart';
import '../../features/leaderboard/data/mock_leaderboard_repository.dart';
import '../../features/leaderboard/domain/i_leaderboard_repository.dart';
import '../../features/player/data/auth_token_store.dart';
import '../../features/player/data/guest_name_generator.dart';
import '../../features/player/data/player_local_data_source.dart';
import '../../features/player/domain/guest_player.dart';
import '../../features/player/domain/i_player_repository.dart';
import '../../features/player/presentation/player_cubit.dart';
import '../audio/audio_service.dart';
import '../audio/audio_settings_local_data_source.dart';
import '../database/hive_config.dart';
import '../network/api_client.dart';
import '../network/auth_interceptor.dart';
import 'progress_seed.dart';
import 'service_locator.config.dart';

/// Global service locator (composition root).
final GetIt sl = GetIt.instance;

/// Wires the whole object graph and seeds local data.
///
/// Requires [HiveConfig.initialise] to have run first (levels/progress boxes
/// open). Opens the player and audio boxes, seeds the levels box on first
/// launch, and then delegates standard constructor-based registrations to
/// [sl.init] generated by `injectable`. Runtime dependencies (guest player
/// identity, authenticated Dio, etc.) are registered manually around the
/// generated initialisation.
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> setupServiceLocator() async {
  // --- Hive boxes (runtime, cannot be generated) ---
  final levelsBox = Hive.box<LevelModel>(HiveConfig.levelsBoxName);
  final progressBox = Hive.box<AppProgressModel>(HiveConfig.progressBoxName);
  final playerBox = await Hive.openBox<dynamic>(PlayerLocalDataSource.boxName);
  await Hive.openBox<dynamic>(AudioSettingsLocalDataSource.boxName);

  _seedLevels(levelsBox);
  seedProgressIfEmpty(progressBox);

  // --- Player (Guest-First identity) ---
  // Wired early: the auth interceptor needs the guest uuid to log in.
  final nameGenerator = GuestNameGenerator();
  final playerDataSource = PlayerLocalDataSource(
    box: playerBox,
    nameGenerator: nameGenerator,
  );
  final GuestPlayer initialPlayer = playerDataSource.getOrCreate();
  sl
    ..registerSingleton<PlayerLocalDataSource>(playerDataSource)
    ..registerSingleton<PlayerCubit>(
      PlayerCubit(dataSource: playerDataSource, initial: initialPlayer),
    );

  // --- Networking (runtime guest uuid) ---
  sl
    ..registerLazySingleton<AuthTokenStore>(
      () => AuthTokenStore(box: playerBox),
    )
    ..registerLazySingleton<AuthInterceptor>(
      () => AuthInterceptor(
        tokenStore: sl<AuthTokenStore>(),
        guestUuid: initialPlayer.uuid,
      ),
    )
    ..registerLazySingleton<ApiClient>(
      () => ApiClient(authInterceptor: sl<AuthInterceptor>()),
    );

  // --- Generated registrations (mappers, repos, use cases, BLoCs, audio) ---
  sl.init();

  // Replace the generated plain Dio with the authenticated one from ApiClient.
  if (sl.isRegistered<Dio>()) {
    sl.unregister<Dio>();
  }
  sl.registerLazySingleton<Dio>(() => sl<ApiClient>().dio);

  // --- AOP decorators: add logging and centralized error handling ---
  // These wraps must happen after sl.init() so the concrete implementations
  // are already registered, and before BLoC registration that consumes them.
  _wrapWithAop<IProgressRepository>(AopProgressRepository.new);
  _wrapWithAop<ILevelRepository>(AopLevelRepository.new);
  _wrapWithAop<ILeaderboardRepository>(AopLeaderboardRepository.new);
  _wrapPlayerRepository();

  // --- BLoCs with function-type parameters cannot be generated by injectable ---
  sl
    ..registerFactory<GameBloc>(
      () => GameBloc(
        loadLevelUseCase: sl<LoadLevelUseCase>(),
        startGameSessionUseCase: sl<StartGameSessionUseCase>(),
        evaluateGameStateUseCase: sl<EvaluateGameStateUseCase>(),
        triggerArrowExitUseCase: sl<TriggerArrowExitUseCase>(),
        undoMoveUseCase: sl<UndoMoveUseCase>(),
        calculateScoreUseCase: sl<CalculateScoreUseCase>(),
        unlockNextLevelUseCase: sl<UnlockNextLevelUseCase>(),
        collisionValidator: sl<CollisionValidator>(),
        audioService: sl<AudioService>(),
      ),
    )
    ..registerFactory<Cube3DGameCubit>(
      () => Cube3DGameCubit(
        triggerArrowExitUseCase: sl<TriggerArrowExitUseCase>(
          instanceName: 'cube3d',
        ),
        collisionValidator: sl<CollisionValidator>(instanceName: 'cube3d'),
        audioService: sl<AudioService>(),
      ),
    );

  // --- Leaderboard (Guest-First) — fallback mock data source ---
  if (!sl.isRegistered<ILeaderboardRepository>()) {
    sl.registerLazySingleton<ILeaderboardRepository>(
      () => MockLeaderboardRepository(),
    );
  }
}

/// Populates the levels box from the code-defined level catalogue on first
/// launch. Keyed by level id so [HiveLevelRepository] can `get(levelId)`.
void _seedLevels(Box<LevelModel> box) {
  if (box.isNotEmpty) return;
  final entries = <int, LevelModel>{
    for (final level in LevelDefinitions.campaignLevels) level.id: level,
  };
  box.putAll(entries);
}

/// Re-registers an existing abstraction [T] wrapped with the supplied AOP
/// decorator factory [decorate].
///
/// Preserves the original concrete instance resolution while ensuring every
/// consumer of [T] receives the decorated version.
void _wrapWithAop<T extends Object>(T Function(T inner) decorate) {
  if (!sl.isRegistered<T>()) return;

  final inner = sl<T>();
  sl.unregister<T>();
  sl.registerSingleton<T>(decorate(inner));
}

/// Special case for the player repository because the composition root
/// registers the concrete [PlayerLocalDataSource] rather than the
/// [IPlayerRepository] abstraction.
void _wrapPlayerRepository() {
  if (!sl.isRegistered<PlayerLocalDataSource>()) return;

  final dataSource = sl<PlayerLocalDataSource>();
  final decorated = AopPlayerRepository(dataSource);
  final existingCubit = sl<PlayerCubit>();

  sl
    ..unregister<PlayerLocalDataSource>()
    ..unregister<PlayerCubit>()
    ..registerSingleton<IPlayerRepository>(decorated)
    ..registerSingleton<PlayerCubit>(
      PlayerCubit(dataSource: decorated, initial: existingCubit.state),
    );
}
