name: Flutter CI/CD

# Se ejecuta al hacer push o pull request en la rama principal
on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    # Usamos la última versión de Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Traer el código del repositorio
      - name: Descargar el código
        uses: actions/checkout@v4

      # 2. Configurar Java (Es un requisito indispensable para compilar en Android)
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Instalar y configurar Flutter
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Usa la versión estable de Flutter
          cache: true       # Activa el caché para que las futuras ejecuciones sean más rápidas

      # 4. Descargar los paquetes (pubspec.yaml)
      - name: Instalar dependencias
        run: flutter pub get

      # 5. Analizar el código en busca de errores de sintaxis o malas prácticas
      - name: Analizar el código (Linter)
        run: flutter analyze

      # 6. Ejecutar las pruebas unitarias (si tienes la carpeta 'test')
      - name: Ejecutar pruebas
        run: flutter test

      # 7. Construir la aplicación para Android
      - name: Construir APK (Android)
        run: flutter build apk --release

      # 8. Guardar el APK resultante en GitHub para poder descargarlo
      - name: Subir el APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 3 # El archivo estará disponible por 3 días

  crear-release:
    name: Crear Release y Subir APK
    needs: build-and-test
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Descargar APK compilado
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/

      - name: Calcular versión y crear Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Crear GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}